name: docker-homeassistant

services:
    # *****************************************************************************
    # homeassistant
    #   Home Assistant is an open-source home automation platform that enables 
    #   users to control and manage smart devices from various brands in a centralized, 
    #   local system. It offers extensive customization, allowing integration with 
    #   devices like lights, thermostats, and sensors through protocols such as 
    #   Zigbee, Z-Wave, and Wi-Fi. Designed for privacy and flexibility, it runs on 
    #   local hardware, giving users full control without relying on cloud services.
    #
    # *****************************************************************************
    homeassistant:
        container_name: homeassistant
        image: lscr.io/linuxserver/homeassistant:latest
        environment:
            - TZ=${TZ_ID}
            - PUID=${PUID:-1000}
            - PGID=${GUID:-1000}
        volumes:
          - config:/config
          - /etc/localtime:/etc/localtime:ro
        ports:
          - 8123:8123
        restart: unless-stopped
        # privileged: true
        network_mode: host

    # *****************************************************************************
    # esphome
    #   ESPHome is a tool for creating custom firmware for ESP8266/ESP32 devices.
    #   It integrates with Home Assistant for device control. The dashboard runs on port 6052.
    #   Access it at http://<your-server-ip>:6052. 
    #
    # *****************************************************************************
    esphome:
        container_name: esphome
        image: "ghcr.io/esphome/esphome"
        environment:
            - TZ=${TZ_ID}
            - PUID=${PUID:-1000}
            - PGID=${PGID:-1000}
            - USERNAME=${ESPHOME_USERNAME}
            - PASSWORD=${ESPHOME_PASSWORD}
        volumes:
          - esphome-config:/config
          - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped
        # privileged: true
        network_mode: host


    # *****************************************************************************
    # code-server
    #   code-server is a self-hosted VS Code instance that runs in the browser.
    #   This setup mounts the Home Assistant config volume as a workspace folder,
    #   allowing you to edit HA configurations directly via the code-server interface.
    #   Access it at http://localhost:8080 (or your host IP:8080).
    #
    # *****************************************************************************
    vscode:
        container_name: vscode
        image: lscr.io/linuxserver/code-server:latest
        environment:
            - TZ=${TZ_ID}
            - PUID=${PUID:-1000}
            - PGID=${GUID:-1000}
            - PASSWORD=${VSC_PASSWORD}
            - DEFAULT_WORKSPACE=/config/workspace
        volumes:
          - config:/config/workspace
          - vscode-config:/config
        ports:
          - 8443:8443
        restart: unless-stopped
        network_mode: host
        
volumes:
    config:
    vscode-config:
    esphome-config: